// Seeds de Skills basadas en ejercicios avanzados de calistenia
// Rank A = ADVANCED, Rank S = EXPERT
// Organizado por las 7 ramas del skill tree

import { SkillCategory, Difficulty, SkillBranch } from '@prisma/client';

export type SkillSeed = {
  name: string;
  description: string;
  category: SkillCategory;
  difficulty: Difficulty;
  branch: SkillBranch;

  // Requirements (0-100 scale)
  requiredStrength: number;
  requiredEndurance: number;
  requiredFlexibility: number;
  requiredBalance: number;

  // Progression system
  strengthRequired: number; // Strength points needed to unlock
  strengthGained: number;   // Strength points gained on completion

  // RPG rewards
  xpReward: number;
  coinReward: number;
  order: number; // Order in branch progression

  // Mission requirements
  requiredReps?: number;
  requiredDuration?: number; // seconds
  requiredDays: number;

  // For linking prerequisites later
  prerequisiteNames?: string[];
};

// ======================
// RAMA: EMPUJE (PUSH)
// ======================

export const empujeSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Archer Push-ups',
    description: 'Push-ups con peso transferido a un lado, progresión hacia one-arm',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'EMPUJE',
    requiredStrength: 60,
    requiredEndurance: 50,
    requiredFlexibility: 30,
    requiredBalance: 40,
    strengthRequired: 30,
    strengthGained: 8,
    xpReward: 60,
    coinReward: 25,
    order: 10,
    requiredReps: 5,
    requiredDays: 3,
    prerequisiteNames: ['Diamond Push-ups'], // Requiere dominar diamond primero
  },
  {
    name: 'Pseudo Planche Push-ups',
    description: 'Push-ups con manos adelantadas, preparación para planche',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'EMPUJE',
    requiredStrength: 70,
    requiredEndurance: 60,
    requiredFlexibility: 40,
    requiredBalance: 50,
    strengthRequired: 40,
    strengthGained: 10,
    xpReward: 80,
    coinReward: 30,
    order: 12,
    requiredReps: 8,
    requiredDays: 5,
    prerequisiteNames: ['Archer Push-ups'],
  },
  {
    name: 'Explosive Push-ups (Clap)',
    description: 'Push-ups explosivas con aplauso en el aire',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'EMPUJE',
    requiredStrength: 65,
    requiredEndurance: 55,
    requiredFlexibility: 25,
    requiredBalance: 35,
    strengthRequired: 35,
    strengthGained: 7,
    xpReward: 65,
    coinReward: 28,
    order: 11,
    requiredReps: 5,
    requiredDays: 3,
    prerequisiteNames: ['Standard Push-ups'],
  },

  // RANK S (EXPERT)
  {
    name: 'One-Arm Push-ups',
    description: 'Push-ups con un solo brazo, máximo control y fuerza',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'EMPUJE',
    requiredStrength: 85,
    requiredEndurance: 70,
    requiredFlexibility: 50,
    requiredBalance: 60,
    strengthRequired: 60,
    strengthGained: 15,
    xpReward: 120,
    coinReward: 50,
    order: 15,
    requiredReps: 3,
    requiredDays: 7,
    prerequisiteNames: ['Archer Push-ups', 'Pseudo Planche Push-ups'],
  },
  {
    name: 'Planche Push-ups',
    description: 'Push-ups desde posición de planche completa',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'EMPUJE',
    requiredStrength: 95,
    requiredEndurance: 80,
    requiredFlexibility: 60,
    requiredBalance: 70,
    strengthRequired: 80,
    strengthGained: 20,
    xpReward: 150,
    coinReward: 75,
    order: 18,
    requiredReps: 3,
    requiredDays: 10,
    prerequisiteNames: ['Pseudo Planche Push-ups', 'Tuck Planche Hold'],
  },
  {
    name: 'Superman Push-ups',
    description: 'Push-ups con brazos y piernas extendidas en el aire',
    category: 'PUSH_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'EMPUJE',
    requiredStrength: 90,
    requiredEndurance: 75,
    requiredFlexibility: 55,
    requiredBalance: 50,
    strengthRequired: 70,
    strengthGained: 18,
    xpReward: 140,
    coinReward: 60,
    order: 16,
    requiredReps: 2,
    requiredDays: 7,
    prerequisiteNames: ['Explosive Push-ups (Clap)'],
  },
];

// ======================
// RAMA: TRACCIÓN (PULL)
// ======================

export const traccionSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Archer Pull-ups',
    description: 'Pull-ups con peso en un brazo, progresión a one-arm',
    category: 'PULL_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'TRACCION',
    requiredStrength: 65,
    requiredEndurance: 55,
    requiredFlexibility: 35,
    requiredBalance: 45,
    strengthRequired: 35,
    strengthGained: 9,
    xpReward: 70,
    coinReward: 30,
    order: 10,
    requiredReps: 5,
    requiredDays: 3,
    prerequisiteNames: ['Wide Grip Pull-ups'],
  },
  {
    name: 'L-sit Pull-ups',
    description: 'Pull-ups manteniendo L-sit durante todo el movimiento',
    category: 'PULL_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'TRACCION',
    requiredStrength: 70,
    requiredEndurance: 65,
    requiredFlexibility: 50,
    requiredBalance: 55,
    strengthRequired: 45,
    strengthGained: 11,
    xpReward: 85,
    coinReward: 35,
    order: 12,
    requiredReps: 5,
    requiredDays: 5,
    prerequisiteNames: ['Pull-ups', 'L-sit Hold'],
  },
  {
    name: 'Typewriter Pull-ups',
    description: 'Pull-ups moviéndose horizontalmente de lado a lado',
    category: 'PULL_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'TRACCION',
    requiredStrength: 68,
    requiredEndurance: 60,
    requiredFlexibility: 40,
    requiredBalance: 50,
    strengthRequired: 40,
    strengthGained: 10,
    xpReward: 75,
    coinReward: 32,
    order: 11,
    requiredReps: 4,
    requiredDays: 4,
    prerequisiteNames: ['Archer Pull-ups'],
  },
  {
    name: 'Muscle-up',
    description: 'Transición explosiva de pull-up a dip en barra',
    category: 'PULL_MOVEMENTS',
    difficulty: 'ADVANCED',
    branch: 'TRACCION',
    requiredStrength: 75,
    requiredEndurance: 65,
    requiredFlexibility: 45,
    requiredBalance: 60,
    strengthRequired: 50,
    strengthGained: 12,
    xpReward: 90,
    coinReward: 40,
    order: 13,
    requiredReps: 3,
    requiredDays: 7,
    prerequisiteNames: ['Pull-ups', 'Dips'],
  },

  // RANK S (EXPERT)
  {
    name: 'One-Arm Pull-ups',
    description: 'Pull-ups con un solo brazo, máxima fuerza de tracción',
    category: 'PULL_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'TRACCION',
    requiredStrength: 90,
    requiredEndurance: 75,
    requiredFlexibility: 55,
    requiredBalance: 65,
    strengthRequired: 70,
    strengthGained: 18,
    xpReward: 140,
    coinReward: 65,
    order: 16,
    requiredReps: 3,
    requiredDays: 10,
    prerequisiteNames: ['Archer Pull-ups', 'Typewriter Pull-ups'],
  },
  {
    name: 'Slow Muscle-up',
    description: 'Muscle-up lento y controlado sin kip',
    category: 'PULL_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'TRACCION',
    requiredStrength: 85,
    requiredEndurance: 80,
    requiredFlexibility: 50,
    requiredBalance: 70,
    strengthRequired: 65,
    strengthGained: 16,
    xpReward: 130,
    coinReward: 55,
    order: 15,
    requiredReps: 3,
    requiredDays: 7,
    prerequisiteNames: ['Muscle-up', 'L-sit Pull-ups'],
  },
  {
    name: 'One-Arm Muscle-up',
    description: 'Muscle-up con un solo brazo, skill definitivo de tracción',
    category: 'PULL_MOVEMENTS',
    difficulty: 'EXPERT',
    branch: 'TRACCION',
    requiredStrength: 98,
    requiredEndurance: 85,
    requiredFlexibility: 60,
    requiredBalance: 75,
    strengthRequired: 90,
    strengthGained: 25,
    xpReward: 200,
    coinReward: 100,
    order: 18,
    requiredReps: 1,
    requiredDays: 14,
    prerequisiteNames: ['One-Arm Pull-ups', 'Slow Muscle-up'],
  },
];

// ======================
// RAMA: CORE
// ======================

export const coreSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Hanging Leg Raises',
    description: 'Elevación de piernas rectas colgado de barra',
    category: 'CORE_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'CORE',
    requiredStrength: 50,
    requiredEndurance: 60,
    requiredFlexibility: 55,
    requiredBalance: 40,
    strengthRequired: 30,
    strengthGained: 8,
    xpReward: 65,
    coinReward: 28,
    order: 10,
    requiredReps: 10,
    requiredDays: 3,
    prerequisiteNames: ['Hanging Knee Raises'],
  },
  {
    name: 'Windshield Wipers',
    description: 'Rotación de piernas side-to-side colgado',
    category: 'CORE_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'CORE',
    requiredStrength: 55,
    requiredEndurance: 65,
    requiredFlexibility: 60,
    requiredBalance: 50,
    strengthRequired: 35,
    strengthGained: 9,
    xpReward: 70,
    coinReward: 30,
    order: 11,
    requiredReps: 8,
    requiredDays: 4,
    prerequisiteNames: ['Hanging Leg Raises'],
  },
  {
    name: 'L-sit Hold',
    description: 'Mantener posición de L sentado con piernas elevadas',
    category: 'CORE_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'CORE',
    requiredStrength: 60,
    requiredEndurance: 70,
    requiredFlexibility: 65,
    requiredBalance: 55,
    strengthRequired: 40,
    strengthGained: 10,
    xpReward: 80,
    coinReward: 35,
    order: 12,
    requiredDuration: 20,
    requiredDays: 5,
    prerequisiteNames: ['Plank'],
  },

  // RANK S (EXPERT)
  {
    name: 'Dragon Flag',
    description: 'Extensión horizontal del cuerpo desde la espalda',
    category: 'CORE_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'CORE',
    requiredStrength: 80,
    requiredEndurance: 85,
    requiredFlexibility: 60,
    requiredBalance: 65,
    strengthRequired: 60,
    strengthGained: 15,
    xpReward: 120,
    coinReward: 50,
    order: 15,
    requiredReps: 5,
    requiredDays: 7,
    prerequisiteNames: ['Hanging Leg Raises', 'L-sit Hold'],
  },
  {
    name: 'V-sit Hold',
    description: 'L-sit avanzado con cuerpo en forma de V',
    category: 'CORE_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'CORE',
    requiredStrength: 70,
    requiredEndurance: 80,
    requiredFlexibility: 75,
    requiredBalance: 70,
    strengthRequired: 55,
    strengthGained: 14,
    xpReward: 110,
    coinReward: 45,
    order: 14,
    requiredDuration: 15,
    requiredDays: 7,
    prerequisiteNames: ['L-sit Hold'],
  },
  {
    name: 'Human Flag',
    description: 'Bandera humana sostenida lateralmente en poste vertical',
    category: 'CORE_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'CORE',
    requiredStrength: 90,
    requiredEndurance: 85,
    requiredFlexibility: 55,
    requiredBalance: 75,
    strengthRequired: 75,
    strengthGained: 20,
    xpReward: 160,
    coinReward: 70,
    order: 17,
    requiredDuration: 10,
    requiredDays: 10,
    prerequisiteNames: ['L-sit Hold', 'Dragon Flag'],
  },
];

// ======================
// RAMA: EQUILIBRIO (HANDSTANDS)
// ======================

export const equilibrioSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Free Handstand',
    description: 'Handstand sin apoyo, balance completo',
    category: 'BALANCE',
    difficulty: 'ADVANCED',
    branch: 'EQUILIBRIO',
    requiredStrength: 60,
    requiredEndurance: 50,
    requiredFlexibility: 55,
    requiredBalance: 75,
    strengthRequired: 35,
    strengthGained: 10,
    xpReward: 85,
    coinReward: 35,
    order: 10,
    requiredDuration: 30,
    requiredDays: 5,
    prerequisiteNames: ['Wall Handstand'],
  },
  {
    name: 'Handstand Push-ups',
    description: 'Push-ups verticales en posición de handstand',
    category: 'BALANCE',
    difficulty: 'ADVANCED',
    branch: 'EQUILIBRIO',
    requiredStrength: 75,
    requiredEndurance: 60,
    requiredFlexibility: 50,
    requiredBalance: 80,
    strengthRequired: 50,
    strengthGained: 12,
    xpReward: 95,
    coinReward: 40,
    order: 12,
    requiredReps: 5,
    requiredDays: 7,
    prerequisiteNames: ['Free Handstand', 'Pike Push-ups'],
  },
  {
    name: 'Handstand Walking',
    description: 'Caminar en handstand con control total',
    category: 'BALANCE',
    difficulty: 'ADVANCED',
    branch: 'EQUILIBRIO',
    requiredStrength: 65,
    requiredEndurance: 55,
    requiredFlexibility: 50,
    requiredBalance: 85,
    strengthRequired: 45,
    strengthGained: 11,
    xpReward: 90,
    coinReward: 38,
    order: 11,
    requiredDuration: 20, // 20 metros
    requiredDays: 7,
    prerequisiteNames: ['Free Handstand'],
  },

  // RANK S (EXPERT)
  {
    name: 'One-Arm Handstand',
    description: 'Handstand con un solo brazo, máximo balance',
    category: 'BALANCE',
    difficulty: 'EXPERT',
    branch: 'EQUILIBRIO',
    requiredStrength: 85,
    requiredEndurance: 70,
    requiredFlexibility: 60,
    requiredBalance: 95,
    strengthRequired: 70,
    strengthGained: 18,
    xpReward: 150,
    coinReward: 65,
    order: 15,
    requiredDuration: 10,
    requiredDays: 14,
    prerequisiteNames: ['Free Handstand', 'Handstand Push-ups'],
  },
  {
    name: 'Press to Handstand',
    description: 'Entrada a handstand desde el suelo sin impulso',
    category: 'BALANCE',
    difficulty: 'EXPERT',
    branch: 'EQUILIBRIO',
    requiredStrength: 88,
    requiredEndurance: 75,
    requiredFlexibility: 80,
    requiredBalance: 90,
    strengthRequired: 75,
    strengthGained: 20,
    xpReward: 160,
    coinReward: 70,
    order: 16,
    requiredReps: 3,
    requiredDays: 10,
    prerequisiteNames: ['Handstand Push-ups', 'L-sit Hold'],
  },
  {
    name: '90-Degree Push-ups',
    description: 'Push-ups con cuerpo horizontal paralelo al suelo',
    category: 'BALANCE',
    difficulty: 'EXPERT',
    branch: 'EQUILIBRIO',
    requiredStrength: 92,
    requiredEndurance: 80,
    requiredFlexibility: 65,
    requiredBalance: 85,
    strengthRequired: 80,
    strengthGained: 22,
    xpReward: 170,
    coinReward: 75,
    order: 17,
    requiredReps: 3,
    requiredDays: 12,
    prerequisiteNames: ['Handstand Push-ups', 'Pseudo Planche Push-ups'],
  },
];

// ======================
// RAMA: TREN INFERIOR
// ======================

export const trenInferiorSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Pistol Squats',
    description: 'Sentadillas a una pierna con control completo',
    category: 'LEG_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'TREN_INFERIOR',
    requiredStrength: 65,
    requiredEndurance: 60,
    requiredFlexibility: 70,
    requiredBalance: 65,
    strengthRequired: 40,
    strengthGained: 10,
    xpReward: 80,
    coinReward: 35,
    order: 10,
    requiredReps: 8,
    requiredDays: 5,
    prerequisiteNames: ['Bulgarian Split Squats'],
  },
  {
    name: 'Shrimp Squats',
    description: 'Sentadilla a una pierna con pie trasero elevado',
    category: 'LEG_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'TREN_INFERIOR',
    requiredStrength: 68,
    requiredEndurance: 65,
    requiredFlexibility: 75,
    requiredBalance: 70,
    strengthRequired: 45,
    strengthGained: 11,
    xpReward: 85,
    coinReward: 38,
    order: 11,
    requiredReps: 8,
    requiredDays: 5,
    prerequisiteNames: ['Pistol Squats'],
  },
  {
    name: 'Dragon Pistol Squats',
    description: 'Pistol squat con pierna extendida al frente',
    category: 'LEG_STRENGTH',
    difficulty: 'ADVANCED',
    branch: 'TREN_INFERIOR',
    requiredStrength: 70,
    requiredEndurance: 68,
    requiredFlexibility: 80,
    requiredBalance: 75,
    strengthRequired: 50,
    strengthGained: 12,
    xpReward: 90,
    coinReward: 40,
    order: 12,
    requiredReps: 6,
    requiredDays: 7,
    prerequisiteNames: ['Pistol Squats'],
  },

  // RANK S (EXPERT)
  {
    name: 'Weighted Pistol Squats',
    description: 'Pistol squats con peso adicional (mancuerna/chaleco)',
    category: 'LEG_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'TREN_INFERIOR',
    requiredStrength: 85,
    requiredEndurance: 80,
    requiredFlexibility: 75,
    requiredBalance: 70,
    strengthRequired: 65,
    strengthGained: 16,
    xpReward: 130,
    coinReward: 55,
    order: 14,
    requiredReps: 5,
    requiredDays: 7,
    prerequisiteNames: ['Pistol Squats', 'Dragon Pistol Squats'],
  },
  {
    name: 'Sissy Squats (Full ROM)',
    description: 'Sentadillas sissy con rango completo de movimiento',
    category: 'LEG_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'TREN_INFERIOR',
    requiredStrength: 75,
    requiredEndurance: 70,
    requiredFlexibility: 85,
    requiredBalance: 65,
    strengthRequired: 55,
    strengthGained: 14,
    xpReward: 110,
    coinReward: 48,
    order: 13,
    requiredReps: 10,
    requiredDays: 7,
    prerequisiteNames: ['Squats'],
  },
  {
    name: 'Jumping Pistol Squats',
    description: 'Pistol squats explosivas con salto',
    category: 'LEG_STRENGTH',
    difficulty: 'EXPERT',
    branch: 'TREN_INFERIOR',
    requiredStrength: 88,
    requiredEndurance: 85,
    requiredFlexibility: 78,
    requiredBalance: 80,
    strengthRequired: 70,
    strengthGained: 18,
    xpReward: 145,
    coinReward: 62,
    order: 15,
    requiredReps: 5,
    requiredDays: 10,
    prerequisiteNames: ['Weighted Pistol Squats', 'Jump Squats'],
  },
];

// ======================
// RAMA: ESTÁTICOS
// ======================

export const estaticosSkills: SkillSeed[] = [
  // RANK A (ADVANCED)
  {
    name: 'Tuck Planche Hold',
    description: 'Planche en posición agrupada',
    category: 'STATIC_ELEMENTS',
    difficulty: 'ADVANCED',
    branch: 'ESTATICOS',
    requiredStrength: 70,
    requiredEndurance: 65,
    requiredFlexibility: 50,
    requiredBalance: 70,
    strengthRequired: 45,
    strengthGained: 12,
    xpReward: 95,
    coinReward: 42,
    order: 10,
    requiredDuration: 15,
    requiredDays: 7,
    prerequisiteNames: ['Pseudo Planche Push-ups'],
  },
  {
    name: 'Advanced Tuck Planche',
    description: 'Planche agrupada con piernas más extendidas',
    category: 'STATIC_ELEMENTS',
    difficulty: 'ADVANCED',
    branch: 'ESTATICOS',
    requiredStrength: 75,
    requiredEndurance: 70,
    requiredFlexibility: 55,
    requiredBalance: 75,
    strengthRequired: 55,
    strengthGained: 14,
    xpReward: 105,
    coinReward: 46,
    order: 11,
    requiredDuration: 12,
    requiredDays: 7,
    prerequisiteNames: ['Tuck Planche Hold'],
  },
  {
    name: 'Tuck Front Lever',
    description: 'Front lever en posición agrupada',
    category: 'STATIC_ELEMENTS',
    difficulty: 'ADVANCED',
    branch: 'ESTATICOS',
    requiredStrength: 68,
    requiredEndurance: 70,
    requiredFlexibility: 45,
    requiredBalance: 65,
    strengthRequired: 48,
    strengthGained: 13,
    xpReward: 100,
    coinReward: 44,
    order: 12,
    requiredDuration: 15,
    requiredDays: 7,
    prerequisiteNames: ['L-sit Pull-ups'],
  },
  {
    name: 'Back Lever',
    description: 'Lever posterior horizontal colgado de barra',
    category: 'STATIC_ELEMENTS',
    difficulty: 'ADVANCED',
    branch: 'ESTATICOS',
    requiredStrength: 65,
    requiredEndurance: 68,
    requiredFlexibility: 60,
    requiredBalance: 70,
    strengthRequired: 50,
    strengthGained: 12,
    xpReward: 92,
    coinReward: 40,
    order: 13,
    requiredDuration: 12,
    requiredDays: 7,
    prerequisiteNames: ['German Hang'],
  },

  // RANK S (EXPERT)
  {
    name: 'Full Planche',
    description: 'Planche completa con cuerpo horizontal',
    category: 'STATIC_ELEMENTS',
    difficulty: 'EXPERT',
    branch: 'ESTATICOS',
    requiredStrength: 95,
    requiredEndurance: 85,
    requiredFlexibility: 65,
    requiredBalance: 90,
    strengthRequired: 85,
    strengthGained: 25,
    xpReward: 180,
    coinReward: 85,
    order: 16,
    requiredDuration: 10,
    requiredDays: 14,
    prerequisiteNames: ['Advanced Tuck Planche', 'Straddle Planche'],
  },
  {
    name: 'Full Front Lever',
    description: 'Front lever completo con piernas extendidas',
    category: 'STATIC_ELEMENTS',
    difficulty: 'EXPERT',
    branch: 'ESTATICOS',
    requiredStrength: 92,
    requiredEndurance: 88,
    requiredFlexibility: 60,
    requiredBalance: 85,
    strengthRequired: 80,
    strengthGained: 23,
    xpReward: 170,
    coinReward: 80,
    order: 15,
    requiredDuration: 10,
    requiredDays: 14,
    prerequisiteNames: ['Tuck Front Lever', 'Advanced Front Lever'],
  },
  {
    name: 'Maltese',
    description: 'Planche con brazos extendidos lateralmente',
    category: 'STATIC_ELEMENTS',
    difficulty: 'EXPERT',
    branch: 'ESTATICOS',
    requiredStrength: 98,
    requiredEndurance: 90,
    requiredFlexibility: 70,
    requiredBalance: 95,
    strengthRequired: 95,
    strengthGained: 30,
    xpReward: 200,
    coinReward: 100,
    order: 18,
    requiredDuration: 5,
    requiredDays: 21,
    prerequisiteNames: ['Full Planche', 'Ring Support Hold'],
  },
  {
    name: 'Victorian',
    description: 'Elemento estático en anillas con cuerpo invertido',
    category: 'STATIC_ELEMENTS',
    difficulty: 'EXPERT',
    branch: 'ESTATICOS',
    requiredStrength: 96,
    requiredEndurance: 88,
    requiredFlexibility: 75,
    requiredBalance: 92,
    strengthRequired: 90,
    strengthGained: 28,
    xpReward: 195,
    coinReward: 95,
    order: 17,
    requiredDuration: 5,
    requiredDays: 21,
    prerequisiteNames: ['Full Front Lever', 'Iron Cross'],
  },
  {
    name: 'Iron Cross',
    description: 'Cruz de hierro en anillas con brazos extendidos',
    category: 'STATIC_ELEMENTS',
    difficulty: 'EXPERT',
    branch: 'ESTATICOS',
    requiredStrength: 94,
    requiredEndurance: 86,
    requiredFlexibility: 68,
    requiredBalance: 88,
    strengthRequired: 82,
    strengthGained: 24,
    xpReward: 175,
    coinReward: 82,
    order: 14,
    requiredDuration: 8,
    requiredDays: 14,
    prerequisiteNames: ['Ring Support Hold', 'Full Planche'],
  },
];

// Skills de calentamiento/movilidad (no rank A/S pero necesarias como prerequisites)
export const calentamientoSkills: SkillSeed[] = [
  {
    name: 'Wrist Mobility Flow',
    description: 'Rutina completa de movilidad de muñecas',
    category: 'MOBILITY',
    difficulty: 'BEGINNER',
    branch: 'CALENTAMIENTO',
    requiredStrength: 0,
    requiredEndurance: 20,
    requiredFlexibility: 40,
    requiredBalance: 10,
    strengthRequired: 0,
    strengthGained: 1,
    xpReward: 10,
    coinReward: 5,
    order: 1,
    requiredDuration: 300, // 5 minutos
    requiredDays: 1,
  },
  {
    name: 'Shoulder Dislocates',
    description: 'Movilidad de hombros con banda o palo',
    category: 'MOBILITY',
    difficulty: 'BEGINNER',
    branch: 'CALENTAMIENTO',
    requiredStrength: 10,
    requiredEndurance: 25,
    requiredFlexibility: 50,
    requiredBalance: 15,
    strengthRequired: 0,
    strengthGained: 2,
    xpReward: 15,
    coinReward: 5,
    order: 2,
    requiredReps: 20,
    requiredDays: 1,
  },
];

// Combinar todas las skills
export const allSkills: SkillSeed[] = [
  ...empujeSkills,
  ...traccionSkills,
  ...coreSkills,
  ...equilibrioSkills,
  ...trenInferiorSkills,
  ...estaticosSkills,
  ...calentamientoSkills,
];

console.log(`Total skills: ${allSkills.length}`);
console.log(`- EMPUJE: ${empujeSkills.length}`);
console.log(`- TRACCION: ${traccionSkills.length}`);
console.log(`- CORE: ${coreSkills.length}`);
console.log(`- EQUILIBRIO: ${equilibrioSkills.length}`);
console.log(`- TREN_INFERIOR: ${trenInferiorSkills.length}`);
console.log(`- ESTATICOS: ${estaticosSkills.length}`);
console.log(`- CALENTAMIENTO: ${calentamientoSkills.length}`);
